# site.*
title: "Just Jason Green"
description: "Web designer, software developer, data scientist, digital artist and creative writer from Melbourne, Australia"
logo: "/assets/images/JustJasonGreen.jpg"
author:
    name: "Jason Green"
    twitter: "JustJasonGreen"
social:
    name: "Jason Green"
    links:
        - "https://github.com/justjasongreen"
        - "https://www.facebook.com/justjasongreen"
        - "https://twitter.com/JustJasonGreen"
facebook:
    admins: "100008472259120"
twitter:
    username: "JustJasonGreen"
google_site_verification: "o_fIkIU1jhO4iBhumOSr0BgHF2q_9OdEkWy22xZLE6k"

# Build Settings
defaults:
    -
        scope:
            path: ""
        values:
            layout: default
            jumbotron_class: "underwater"
            title_separator: " @ "
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: post
            author: "jason"
            comments: true
    -
        scope:
            path: "blog"
        values:
            jumbotron_class: "writing"
            title: "Latest Blog Posts"
    -
        scope:
            path: "blog"
            type: "posts"
        values:
            image: "/assets/images/pexels-photo-24193.jpg"
    -
        scope:
            path: "projects"
        values:
            jumbotron_class: "tools"
            title: "Latest Project Updates"
    -
        scope:
            path: "projects"
            type: "posts"
        values:
            image: "/assets/images/construction-work-carpenter-tools.jpg"
exclude:
    - Dockerfile
    - Gemfile
    - Gemfile.lock
    - README.md
    - docker-compose.yml
    - vendor
gems:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
sass:
    style: :compressed
